name: Publish AMD64 & ARM64 Docker image

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.7
          
      - name: Log in to Github
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
           ghcr.io/${{ github.repository }}
          
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: linux/amd64, linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./Server
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/almir1904/remotely:latest
          labels: ${{ steps.meta.outputs.labels }}
